###
POST http://localhost:4000/products-api/product
Content-Type: application/json

{
    "productName":"mobile",
    "price":70000,
    "brand":"apple"
}

###
POST http://localhost:4000/products-api/product
Content-Type: application/json

{
    "productName":"mobile",
    "price":8000,
    "brand":"samsung"
}
###
POST http://localhost:4000/users-api/users
Content-Type: application/json

{
    "name":"shiva",
    "email":"nandashiva.@gmail.com",
    "password":"dmart_shiva",
    "cart":[]
}

###
PUT http://localhost:4000/users-api/user-cart/user-id/6981a2e741e79def98f4845d/product-id/6981a2e541e79def98f4845a

###
GET http://localhost:4000/users-api/users/6981a2e741e79def98f4845d